### ISSUE TITLE
SyntaxError on launch of script

### ISSUE THREAD

**Issue by bgauthier555** [BALKANGraph/export-service#1]
node -v
v6.17.1

When I call node node_modules/@balkangraph/export-service/app.js I get the following error :
 
node_modules/@balkangraph/export-service/app.js:183
        (async () => {
               ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by CircleHe** [comment]
Try to upgrade node to v7.x.x as least, which supports async
