### ISSUE TITLE
Cannot run export-service in Docker Container

### ISSUE THREAD

**Issue by joce007** [BALKANGraph/export-service#5]
Hi,

I'm trying to run the export-service in Docker.  I'm able to built and run the Docker image and see the index.html page but as soon as I try to export to PDF button, I`ve got a connection refused. .  It seems to be related to puppeteer library (see call stack below).  

I've made some research and followed some recommendations on this site https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker without success.  It seems to be a problem between Chromium and Puppeteer but don't know how to fix it.

CALLSTACK: 
```
(node:1) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:8080/appdata/2020-3-20-15-23-15~18a445f1-b695-4217-b657-c8549cdd450c.svg
    at navigate (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:94:17)
    at async Frame.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:406:12)
    at async Page.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:12)
    at async /wwwnodes/npm/node_modules/@balkangraph/export-service/app.js:187:13
  -- ASYNC --
    at Frame.<anonymous> (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:112:23)
    at /wwwnodes/npm/node_modules/@balkangraph/export-service/app.js:187:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info: /wwwnodes/npm/node_modules/@balkangraph/export-service/appdata/2020-3-20-15-25-15~c53e9523-c12a-4343-a56a-70f6b973c0e2.svg file was saved; width: 1185; height: 860; {"timestamp":"2020-04-20T15:25:15.511Z"}
(node:1) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_REFUSED at http://localhost:8080/appdata/2020-3-20-15-25-15~c53e9523-c12a-4343-a56a-70f6b973c0e2.svg
    at navigate (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:94:17)
    at async Frame.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/FrameManager.js:406:12)
    at async Page.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:12)
    at async /wwwnodes/npm/node_modules/@balkangraph/export-service/app.js:187:13
  -- ASYNC --
    at Frame.<anonymous> (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/Page.js:674:49)
    at Page.<anonymous> (/wwwnodes/npm/node_modules/@balkangraph/export-service/node_modules/puppeteer/lib/helper.js:112:23)
    at /wwwnodes/npm/node_modules/@balkangraph/export-service/app.js:187:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Please advice!
Thanks!

**Comment by ZornitsaSerbezova** [comment]
Hi Joce,

This error is not related to the export-service. You could contact the docker developers for help.

Regards,
Zornitsa

**Comment by glostis** [comment]
Hi @joce007 !

Like you I tried to run the export-service in a Docker container on my server, and I've managed to run it successfully using the following Dockerfile:

```dockerfile
FROM node:latest

# Dependencies for puppetteer/chromium
# Taken from https://medium.com/@ssmak/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-c1918b75acc3
RUN apt-get update && apt-get install -y \
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget

# Taken from the README of https://github.com/BALKANGraph/export-service
RUN npm i @balkangraph/export-service
CMD ["node", "node_modules/@balkangraph/export-service/app.js"]
```
I then run this container exposing its 1337 port, and everything runs smoothly!

**Comment by joce007** [comment]
Hi @glostis,

I`ve tried your Dockerfile and I've got the same exact error.  The index.html page loads on port 1337 but as soon as a press the export button (PDF), I still got the same issue as describe initially.  It seems to be a question of access / privileges and was never able to found a solution.  I don't understands why you don't get the same error.

My Docker settings are:  
- Docker Windows Desktop Edition: 2.3.1.0 (45408) - Channel: Edge
- Engine: 19.0.38
- Running in Linux Containers

Other than your docker file, have you done something else ?

**Comment by glostis** [comment]
I just build the Dockerfile above, build it (`docker build -t balkan .`), and then run it using
```
docker run -it -p 1337:1337 balkan
```

I then visit http://localhost:1337/index.html and the export PDF just works.

I'm on a Linux machine and don't have any experience with Windows, maybe there's something specific to Windows as far as Docker is concerned?

**Comment by joce007** [comment]
I've finally found the issue, it has to do with the hostname that I was using (localhost).  This post 
[https://github.com/puppeteer/puppeteer/issues/2791](https://github.com/puppeteer/puppeteer/issues/2791) provides me the hint to fix it.  I've used the proper hostname defined for 127.0.0.1 according to the Windows hosts file.  It wasn't localhost but rather kubernetes.docker.internal.  The strange thing is localhost was working to display the index.html page but not for the PDF output result.
